[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=src -vv"

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
fail_under = 85

[tool.isort]
profile = "black"
